/**
 * Signed payload accepted by POST /register.
 */
export interface RegisterRequest {
	/** Stable device identity generated by the iOS app. */
	deck_id: string;
	/** Unix timestamp in seconds used for replay-window validation. */
	timestamp: number;
	/** APNs token. Required on first registration, optional on status-only updates. */
	device_token?: string;
	/** Push enablement flag. Defaults to enabled when omitted. */
	is_enabled?: boolean;
	/** List of server identifiers this device should subscribe to. */
	server_ids?: string[];
}

/**
 * Request body for POST /webhook/:token/rotate.
 */
export interface WebhookRotateRequest {
	server_id: string;
}

/**
 * Incoming webhook payload emitted by the Unraid plugin.
 */
export interface WebhookPayload {
	title?: string;
	message?: string;
	importance?: string;
	timestamp?: string;
	link?: string;
}

/**
 * Per-device APNs send result after retry processing.
 */
export interface ApnsSendResult {
	/** Redacted token for safe logging/response diagnostics. */
	token: string;
	ok: boolean;
	status: number | null;
	reason: string;
	/** Number of attempts actually made for this token. */
	attempts: number;
	retryable: boolean;
}

/**
 * Aggregated delivery stats for one webhook dispatch batch.
 */
export interface WebhookDispatchSummary {
	total: number;
	success: number;
	failed: number;
	retried: number;
	/** Count of APNs 410 responses that triggered token cleanup. */
	invalid_token_removed: number;
}

/**
 * Final APNs dispatch response model used by webhook handlers.
 */
export interface ApnsDispatchResult {
	summary: WebhookDispatchSummary;
	results: ApnsSendResult[];
}

/**
 * Successful register-service result with assigned webhook tokens.
 */
export interface RegisterServiceSuccess {
	ok: true;
	tokens: Record<string, string>;
}

/**
 * Business failure for register-service when the device is not yet seeded.
 */
export interface RegisterServiceFailure {
	ok: false;
	status: 409;
	code: 'DEVICE_NOT_REGISTERED';
	message: string;
}

export type RegisterServiceResult = RegisterServiceSuccess | RegisterServiceFailure;

/**
 * Server and recipients resolved from a webhook token lookup.
 */
export interface WebhookDispatchContext {
	serverId: string;
	deviceTokens: string[];
}

/**
 * APNs payload shape sent to Apple Push Notification service.
 */
export interface ApnsPayload {
	aps: {
		alert: {
			title: string;
			body: string;
		};
		sound: 'default';
		'interruption-level': 'time-sensitive' | 'active';
		'thread-id': string;
		'mutable-content': 1;
	};
	server_id: string;
	importance?: string;
	timestamp?: string;
	link?: string;
}
